version: "3.8"
services:
  # Symfony apache project container
  www:
    build: docker/php
    container_name: symfony
    ports:
      - "8000:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - symfony

networks:
  symfony:

volumes:
  db-data:
